package com.example.noise.service;

import com.baomidou.mybatisplus.core.metadata.IPage;
import com.example.noise.entity.Report;

/**
 * 报告生成 Service 接口 — P2-3 定时报告生成
 */
public interface ReportService {

  /**
   * 分页查询报告列表，按创建时间倒序
   *
   * @param pageNum  页码
   * @param pageSize 每页条数
   * @return 报告分页结果
   */
  IPage<Report> queryPage(int pageNum, int pageSize);

  /**
   * 查询报告详情
   *
   * @param id 报告 ID
   * @return 报告实体
   */
  Report getDetail(Long id);

  /**
   * 手动生成报告（管理员操作）
   * 聚合 noise_record + alert_log 统计，生成 Markdown 格式报告，存入 report 表
   *
   * @param reportPeriod 报表周期：DAILY / WEEKLY / MONTHLY
   * @param periodStart  统计起始时间，格式 yyyy-MM-dd HH:mm:ss
   * @param periodEnd    统计结束时间，格式 yyyy-MM-dd HH:mm:ss
   * @return 生成的报告实体
   */
  Report generateReport(String reportPeriod, String periodStart, String periodEnd);

  /**
   * 配置报告定时生成计划（P2 占位，记录配置即可）
   *
   * @param reportPeriod 报表周期
   * @param generateTime 计划生成时间，格式 HH:mm
   */
  void scheduleConfig(String reportPeriod, String generateTime);

  /**
   * 每日自动生成前一日报告（@Scheduled cron: "0 0 6 * * ?" 每日 6:00 执行）
   * 自动生成前一天 (00:00:00 ~ 23:59:59) 的 DAILY 报告
   */
  void autoGenerateDailyReport();
}
